# Gems
gems:
  - jekyll-archives

# Site settings
title: Nicolás Siplis
email: nicolas.siplis@gmail.com
description: "The boringly exciting adventures of a newbie programmer"
baseurl: ""
url: ""
twitter_username: nicolas_siplis
github_username: nicolas-siplis
facebook_username:
reddit_username: nicolas-siplis

jekyll-archives:
  enabled: all
  layout: archive
  permalinks:
    year: '/:year/'
    month: '/:year/:month/'
    day: '/:year/:month/:day/'
    tag: '/tag/:name/'
    category: '/category/:name/'

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
