# Site settings
title: Nicolás Siplis
header-img: img/home-bg.jpg
email: nicolas.siplis@gmail.com
description: "The boringly exciting adventures of a newbie programmer"
baseurl: "https://nicolas-siplis.github.io/"
url: ""
twitter_username: nicolas_siplis
github_username: nicolas-siplis
facebook_username: nicolassiplis

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
